"""Backward-compatible facade for the domain model modules."""

from .agent_models import (
    AgentDecision,
    AgentState,
    DataQuality,
    Dimension,
    EditorialOptions,
    Evidence,
    FinalAnalysis,
    Generation,
    IntegratedView,
    PendingActionResponse,
    ReportPublication,
    RequestIntentAssessment,
    ToolCall,
    ToolResult,
    UserIntent,
)
from .market_models import (
    AssetResolution,
    Bar,
    CompanyType,
    DiscardedHistoryReason,
    DiscardedHistoryRow,
    ErrorInfo,
    MarketHistory,
    QuoteSnapshot,
)
from .model_base import TICKER_PATTERN, CalendarDate, HistoryRange, Model, Ticker, now
from .technical_models import (
    IndicatorBasis,
    Signal,
    TechnicalAssessment,
    TechnicalMetrics,
    TechnicalSignal,
)

__all__ = [
    "AgentDecision",
    "AgentState",
    "AssetResolution",
    "Bar",
    "CalendarDate",
    "CompanyType",
    "DataQuality",
    "Dimension",
    "DiscardedHistoryReason",
    "DiscardedHistoryRow",
    "EditorialOptions",
    "ErrorInfo",
    "Evidence",
    "FinalAnalysis",
    "Generation",
    "HistoryRange",
    "IndicatorBasis",
    "IntegratedView",
    "MarketHistory",
    "Model",
    "PendingActionResponse",
    "QuoteSnapshot",
    "ReportPublication",
    "RequestIntentAssessment",
    "Signal",
    "TICKER_PATTERN",
    "TechnicalAssessment",
    "TechnicalMetrics",
    "TechnicalSignal",
    "Ticker",
    "ToolCall",
    "ToolResult",
    "UserIntent",
    "now",
]
